apiVersion: v1
kind: Service

metadata:
  name: elasticsearch-discovery
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
    role: master
    
spec:
  ports:
  - port: 9300
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging
    role: master
